# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
# version: 1.0

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: source/conf.py


# formats:
#   - pdf
#   - epub

